version: '3.8'

services:
  # E-Voting Application
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: evote-app
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:/app/data/production.db
      - NEXTAUTH_URL=https://vote.smkn2malinau.sch.id
      - NEXTAUTH_SECRET=your-super-secure-secret-key-change-this-in-production
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=SecureAdminPass2024!
      - COMMITTEE_USERNAME=committee
      - COMMITTEE_PASSWORD=SecureCommitteePass2024!
      - UPLOAD_DIR=/app/uploads
      - MAX_FILE_SIZE=5242880
    volumes:
      - ./data:/app/data
      - ./uploads:/app/uploads
    networks:
      - evote-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: evote-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/sites-available:/etc/nginx/sites-available:ro
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./uploads:/var/www/uploads:ro
      - ./logs/nginx:/var/log/nginx
    networks:
      - evote-network
    depends_on:
      app:
        condition: service_healthy

  # Redis for Session Storage (Optional)
  redis:
    image: redis:7-alpine
    container_name: evote-redis
    restart: unless-stopped
    command: redis-server --appendonly yes --requirepass SecureRedisPass2024!
    volumes:
      - redis_data:/data
    networks:
      - evote-network
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  evote-network:
    driver: bridge
    name: evote-network

volumes:
  redis_data:
    driver: local